
# Example configuration
watching:
  - target: ./test/...
    notifications:
      - notify: slack
        event: all
        options:
          channel: "#test"
          username: "fofiwano"
          webhook_url: "https://hooks.slack.com/services/..."
          icon_emoji: ":monkey_face:"
          footer: "fofiwano"
      - notify: http
        event: write
        options:
          url: http://www

  - target: ./test2/...
    notifications:
      - notify: http
        event: write
        options:
          url: http://test.de
