
# Example configuration
watching:
  - target: ./test/...
    notifications:
      - notify: slack
	event: all
        options:
          channel: "#test"
          user: fofiwano
          webhook: https://...
      - notify: http
	event: write
        options:
          uri: http://www

  - target: ./test2/...
    notifications:
      - notify: http
	event: write
        options:
          uri: http://test.de
